In [1]:
import numpy as np

In [2]:
myarray=np.array([3,4,3,434])

In [3]:
myarray

array([  3,   4,   3, 434])

In [4]:
myarray.dtype

dtype('int32')

In [5]:
myarray[3]

434

# different method for create numpy array

In [6]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [7]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
arr.size

9

In [9]:
arr.shape

(3, 3)

In [10]:
zeros=np.zeros((2,5))

In [11]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [12]:
rng=np.arange(15)

In [13]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [14]:
rng.dtype

dtype('int32')

In [15]:
lspace=np.linspace(1,50,10)

In [16]:
lspace

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [57]:
lspace1=np.linspace(1,10,5)

In [59]:
lspace1

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [17]:
empty=np.empty((4,5))

In [18]:
empty

array([[1.28422138e-311, 6.27463370e-322, 0.00000000e+000,
        0.00000000e+000, 7.56571287e-307],
       [5.30276956e+180, 1.57076922e-076, 4.57222315e-071,
        5.06793392e-086, 3.35708708e-143],
       [6.01433264e+175, 6.93885958e+218, 5.56218858e+180,
        3.94356143e+180, 1.20129652e-075],
       [1.27845526e+165, 2.52414930e-052, 2.62040465e+180,
        4.40878795e-143, 1.50008929e+248]])

In [61]:
empty.shape

(4, 5)

In [19]:
empty_l=np.empty_like(lspace)

In [20]:
empty_l

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [62]:
empty_l.shape

(10,)

In [21]:
de=np.identity(5)

In [22]:
de

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [23]:
arr=np.arange(99)

In [24]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [25]:
arr.reshape(3, 33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [26]:
arr= arr.reshape(33,3)

In [27]:
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29],
       [30, 31, 32],
       [33, 34, 35],
       [36, 37, 38],
       [39, 40, 41],
       [42, 43, 44],
       [45, 46, 47],
       [48, 49, 50],
       [51, 52, 53],
       [54, 55, 56],
       [57, 58, 59],
       [60, 61, 62],
       [63, 64, 65],
       [66, 67, 68],
       [69, 70, 71],
       [72, 73, 74],
       [75, 76, 77],
       [78, 79, 80],
       [81, 82, 83],
       [84, 85, 86],
       [87, 88, 89],
       [90, 91, 92],
       [93, 94, 95],
       [96, 97, 98]])

In [28]:
arr = arr.ravel() #make array as it is when it is created

In [29]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [30]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [31]:
arr.sum(axis=0)

array([12, 15, 18])

In [32]:
arr.sum(axis=1)

array([ 6, 15, 24])

In [33]:
arr.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [34]:
for item in arr.flat:
    print(item)

1
2
3
4
5
6
7
8
9


In [35]:
arr.ndim

2

In [36]:
one=np.array([1,3,5,3423,23])

In [37]:
one.argmax()

3

In [38]:
one.argmin()

0

In [39]:
one.argsort()

array([0, 1, 2, 4, 3], dtype=int64)

In [40]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [41]:
arr.argmax()

8

In [42]:
arr.argmax(axis=0)

array([2, 2, 2], dtype=int64)

In [43]:
arr.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]], dtype=int64)

In [44]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [45]:
arr.argsort(axis=0)

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2]], dtype=int64)

In [46]:
arr1=np.array([[2, 3, 1],
       [5, 4, 0],
       [7, 6, 1]])

In [47]:
arr1

array([[2, 3, 1],
       [5, 4, 0],
       [7, 6, 1]])

In [48]:
arr+arr1

array([[ 3,  5,  4],
       [ 9,  9,  6],
       [14, 14, 10]])

In [49]:
np.sqrt(arr)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [50]:
arr.sum()

45

In [63]:
np.where(arr>=7)

(array([2, 2, 2], dtype=int64), array([0, 1, 2], dtype=int64))

In [52]:
np.count_nonzero(arr1)

8

In [53]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [54]:
np.diag([1,2,3,4])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [55]:
np.random.rand(5)

array([0.60598026, 0.72200991, 0.39919427, 0.91392342, 0.97803551])

In [56]:
np.array([1+2j,2+3j])

array([1.+2.j, 2.+3.j])